# \u4EFB\u52A1\u7EBF\u7A0B\u6C60\u914D\u7F6E @Async \u4F7F\u7528
spring.task.execution.thread-name-prefix=async-
spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=16
spring.task.execution.pool.keep-alive=60s
spring.task.execution.pool.queue-capacity=10000

# \u5B9A\u65F6\u4EFB\u52A1\u7EBF\u7A0B\u6C60\u914D\u7F6E @Scheduled \u4F7F\u7528
spring.task.scheduling.pool.size=8
spring.task.scheduling.thread-name-prefix=scheduled-

# \u542F\u7528\u865A\u62DF\u7EBF\u7A0B
spring.threads.virtual.enabled=true
