# \u4FEE\u6539\u9ED8\u8BA4\u6570\u636E\u5E93\u4E8B\u52A1\u9694\u79BB\u7EA7\u522B
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

mybatis-plus.global-config.banner=false
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
mybatis-plus.global-config.db-config.id-type=auto
mybatis-plus.global-config.db-config.logic-delete-field=delete_time
mybatis-plus.global-config.db-config.logic-delete-value=NOW()
mybatis-plus.global-config.db-config.logic-not-delete-value=NULL
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
mybatis-plus.type-handlers-package=cn.mindit.atom.mybatisplus.handler
